swagger: '2.0'
host: api.pikle.it
basePath: /
schemes:
  - http
paths:
  /api/auth:
    post:
      bodyContentType: application/json
      description: Based on API Key auth, exchanged for a JWT.
      responses:
        '200':
          description: JWT token.
  /api/doc:
    get:
      bodyContentType: application/json
      description: API documentation
      responses:
        '200':
          description: Successful response
  /auth:
    post:
      bodyContentType: application/json
      description: >-
        Based on standard user/pass login. For API-based login, please use 'POST
        /api/auth'.
      responses:
        '200':
          description: Pong!
  /logout:
    post:
      bodyContentType: application/json
      description: End a session.
      responses:
        '200':
          description: ''
  /metadata/chainSyncs:
    get:
      bodyContentType: application/json
      description: Get a list of recent chain syncs.
      responses:
        '200':
          description: ''
  /ping:
    get:
      bodyContentType: application/json
      description: Ping pong!
      responses:
        '200':
          description: Pong!
          schema:
            type: String
  /song:
    post:
      bodyContentType: application/json
      description: Submit a Song for Processing
      responses:
        '200':
          description: ''
  /song/:id:
    get:
      bodyContentType: application/json
      description: Get the song's metadata.
      responses:
        '200':
          description: ''
    delete:
      bodyContentType: application/json
      description: >-
        Delete a song from the system. Note that once on chain, a hash cannot be
        deleted.
      responses:
        '200':
          description: ''
  /song/:id/art:
    put:
      bodyContentType: application/json
      description: >-
        Upload new art for a song. Note that this will only change the NFT image
        if not on IPFS!
      responses:
        '200':
          description: ''
  /song/:id/footprint:
    post:
      bodyContentType: application/json
      description: Send audio footprint to the private chain.
      responses:
        '200':
          description: ''
  /song/:id/metadata:
    post:
      bodyContentType: application/json
      description: Sends local metadata to the private chain for hashing.
      responses:
        '200':
          description: ''
  /song/:id/nft:
    post:
      bodyContentType: application/json
      description: Mints an NFT for a given song ID.
      responses:
        '200':
          description: ''
  /song/:id/nftMetadata:
    get:
      bodyContentType: application/json
      description: NFT metadata file for a song, either from local or from IPFS.
      responses:
        '200':
          description: ''
  /wallet/:address:
    get:
      bodyContentType: application/json
      description: Get wallet information (without private key) for the user.
      responses:
        '200':
          description: ''

